import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { Board } from "../src/board.js";
import { readWorkflow } from "../src/workflow.js";
import { uid } from "../src/workflow-schema.js";

for (const malformed of [false, true]) test(malformed ? "reconciliation preserves diagnostics through malformed configuration and resumes after repair" : "accepted OpenSpec delta reconciles with canonical content without losing validated lineage", async (t) => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "planboard-reconcile-")));
  const write = (name, text) => { fs.mkdirSync(path.dirname(path.join(dir, name)), { recursive: true }); fs.writeFileSync(path.join(dir, name), text); };
  write("PLAN.md", "# Change {#plan}\n\n- [ ] Implement behavior {#impl}\n");
  write("app/code.js", "export const value = 'new';\n");
  const old = "### Requirement: Behavior\nOld behavior.\n\n#### Scenario: Success\nWorks.\n";
  const proposed = old.replace("Old behavior.", "New behavior.");
  write("openspec/specs/core/spec.md", "## Requirements\n" + old);
  write("openspec/changes/update-core/specs/core/spec.md", "## MODIFIED Requirements\n" + proposed);
  const config = { schema_version: 1, workspace: ".", openspec: "openspec", sources: [], tasks: {}, checks: {} };
  write("PLAN.workflow.json", JSON.stringify(config));
  const board = new Board(path.join(dir, "PLAN.md")); board.refresh();
  t.after(async () => { await board.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  const call = (family, action, data = {}) => board.workflow.mutate(family, action, { idempotency_key: uid("op"), ...data });
  const req = Object.values(board.workflow.state.specs.requirements).find((r) => r.status === "proposed");
  config.tasks.impl = { change: "update-core", requirements: [req.id], criteria: [{ id: "AC-1", text: "Works" }], scope: ["app"], outputs: ["code"], checks: ["CHECK-1"] };
  config.checks["CHECK-1"] = { method: "manual", criteria: ["AC-1"], required: true };
  call("spec", "configure", { config });
  const worker = call("worker", "register", { host: "codex", label: "coordinator", workspace: dir });
  const coordinator = call("worker", "coordinator", { worker: worker.id, worker_token: worker.worker_token });
  const run = call("run", "create", { task: "impl", worker: worker.id, token: coordinator.token });
  const attempt = call("worker", "claim", { run: run.id, worker: worker.id, worker_token: worker.worker_token });
  const submitted = call("run", "submit", { attempt: attempt.id, token: attempt.token });
  const check = call("validate", "start", { job: submitted.jobs[0].id, worker: worker.id, worker_token: worker.worker_token });
  call("validate", "result", { job: check.job.id, token: check.token, outcome: "passed", evidence: [{ name: "proof.txt", text: "Observed working behavior" }], criteria: [{ id: "AC-1", outcome: "passed" }] });
  const accepted = call("spec", "accept", { change: "update-core" });
  assert.equal(accepted.phase, "ready_to_reconcile");
  let started = call("spec", "reconciliation-start", { change: "update-core", operation_key: "archive-one", execution_id: "native-one" });
  assert.throws(() => call("spec", "accept", { change: "update-core" }), /reconciliation is already running/);
  assert.throws(() => call("spec", "reconciliation-start", { change: "update-core", operation_key: "archive-two", execution_id: "native-two" }), /reconciling/);
  if (malformed) {
    const invalid = structuredClone(config); invalid.tasks.impl.requirements = "not-an-array";
    write("PLAN.workflow.json", JSON.stringify(invalid));
    const failed = call("spec", "reconciled", { change: "update-core", operation_key: "archive-one", token: started.token, outcome: "passed", evidence: [{ name: "diagnostics.txt", text: "Native operation diagnostics retained despite invalid configuration" }] });
    assert.equal(failed.phase, "ready_to_reconcile");
    assert.equal(failed.attempts[0].outcome, "inconclusive");
    assert.ok(failed.attempts[0].problems.length);
    assert.equal(board.workflow.evidence(failed.attempts[0].evidence[0].id).name, "diagnostics.txt");
    write("PLAN.workflow.json", JSON.stringify(config));
    started = call("spec", "reconciliation-start", { change: "update-core", operation_key: "archive-one", execution_id: "native-retry" });
  }
  // Simulate the native OpenSpec archive output, not a Planboard source rewrite.
  write("openspec/specs/core/spec.md", "## Requirements\n" + proposed);
  fs.rmSync(path.join(dir, "openspec/changes/update-core"), { recursive: true });
  board.workflow.reconcile();
  const result = call("spec", "reconciled", { change: "update-core", operation_key: "archive-one", token: started.token, outcome: "passed", evidence: [{ name: "archive.txt", text: "Native archive applied the validated delta" }] });
  assert.equal(result.phase, "reconciled");
  assert.equal(call("spec", "reconciled", { change: "update-core", outcome: "error" }).phase, "reconciled");
  assert.equal(board.workflow.publicState().tasks[0].acceptance, "accepted");
  assert.equal(board.workflow.state.specs.requirements[req.id].status, "delivered");
  assert.equal(readWorkflow(board.path, board.dir, board.model).tasks[0].acceptance, "accepted");
  assert.equal(board.workflow.evidence(result.attempts.at(-1).evidence[0].id).name, "archive.txt");
  const taskHistory = board.workflow.history({ task: "impl" }).events;
  assert.ok(taskHistory.some((e) => e.type === "run.submit"));
  assert.ok(taskHistory.some((e) => e.type === "validate.start"));
  assert.ok(board.workflow.history({ requirement: req.id }).events.some((e) => e.type === "validate.result"));
  fs.writeFileSync(path.join(dir, "PLAN.workflow.json"), "invalid JSON");
  const offline = readWorkflow(board.path, board.dir, board.model);
  assert.equal(offline.tasks[0].acceptance, "stale");
  assert.match(offline.error, /Invalid workflow JSON/);
  const online = board.workflow.publicState();
  assert.ok(Object.values(online.artifacts).every((a) => a.stale));
  assert.ok(Object.values(online.results).every((r) => r.fresh === false));
});
